version: 0.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
- ps: "nuget restore ProjectManagmentSoftware.sln\n\n$contentAssembly = Get-Content ProjectManagmentSoftware\\SharedAssemblyInfo.cs\n\"'\"+$contentAssembly+\"'\" -match '\\[assembly: AssemblyVersion\\(\\\"(?<major>\\d+).(?<minor>\\d+).(?<patch>\\d+).(\\*)\\\"\\)\\]'\n$matchVar = $matches\n$versionNew = \"{0}.{1}.{2}\" -f $matchVar[\"major\"],$matchVar[\"minor\"],$matchVar[\"patch\"]\n\n\n$contentInstaller = Get-Content Installer\\Installer.iss\n\"'\"+$contentInstaller+\"'\" -match '\\#define MyAppVersion \\\"(?<major>\\d+).(?<minor>\\d+).(?<patch>\\d+)\\\"'\n$matchVar1 = $matches\n$versionOld = \"{0}.{1}.{2}\" -f $matchVar1[\"major\"],$matchVar1[\"minor\"],$matchVar1[\"patch\"]\n\n\n(Get-Content Installer\\Installer.iss) | \nForeach-Object {$_ -replace $versionOld,$versionNew}  | \nOut-File -Encoding UTF8 Installer\\Installer.iss\n\n$contentCI = Get-Content appveyor.yml\n\"'\"+$contentCI+\"'\" -match 'release: MK-v(?<major>\\d+).(?<minor>\\d+).(?<patch>\\d+)'\n$matchVar2 = $matches\n$versionOldCI = \"{0}.{1}.{2}\" -f $matchVar2[\"major\"],$matchVar2[\"minor\"],$matchVar2[\"patch\"]\n\n(Get-Content appveyor.yml) | \nForeach-Object {$_ -replace $versionOldCI,$versionNew} | \nOut-File -Encoding UTF8 appveyor.yml"
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: packages\Tools.InnoSetup.5.5.6\tools\iscc "Installer\Installer.iss"
artifacts:
- path: Installer\ProjectManagmentSoftwareInstall\
  name: PMSInstall.exe
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: pms Release
  auth_token:
    secure: pDn59SKEUUJINiKvhTnsOMufSfa5nLAG8uViWpCqB1O2t+tuBgUtLjYV7X/U2vff
  artifact: PMSInstall.exe
  on:
    branch: master
    configuration: Release
    appveyor_repo_tag: true